dist: xenial
language: python
cache: pip

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.6"
      env: TOXENV=with-sslib-master

  allow_failures:
    - python: "3.6"
      env: TOXENV=with-sslib-master

install:
  - pip install tox coveralls

script:
  - tox

after_success:
  # Workaround to get coverage reports with relative paths.
  # FIXME: Consider refactoring the tests to not require the test aggregation
  # script being invoked from the `tests` directory, so that `.coverage` is
  # written to and .coveragrc can also reside in the project root directory, as
  # is the convention.
  - cp tests/.coverage .
  - coveralls --rcfile=tests/.coveragerc
